src/main.js
=> support ime composition

src/main.js
=> fix param error

src/main.js
=> fix typo error

package.json
=> Fix #116: devDependencies中重复依赖

src/util/is-native.js, src/util/next-tick.js
调研的详情如 https://github.com/ecomfe/san/issues/141
一开始想用requestAnimationFrame，但是经过在vue提issue问他们有没有考虑过使用rAF来实现nextTick，尤雨溪的回答是`nextTick exists primarily for scheduling rather than deferring work`。因此我也放弃使用rAF了。。
=> update nextTick method

src/view/component.js, src/view/element-attached.js, test/element-event.spec.js
=> feat:native events

src/view/compile-js-source.js, src/view/get-prop-handler.js
=> fix: multiple spelling mistakes

src/runtime/data.js
=> 建议：this.data.push、unshift添加符合javascript数组对应行为的返回值

CHANGELOG.md, src/view/component.js, test/component.spec.js
=> Close #191

src/view/element-attached.js
和vue的这个问题应该是同一个问题：https://github.com/vuejs/vue/issues/5387
=> fix:iOS部分浏览器下，双绑失效的问题

src/util/next-tick.js
=> remove fn.toString() in reg

src/view/compile-js-source.js, src/view/component.js, src/view/create-node.js, src/view/create-reverse-node.js
=> Add getComponentType for san.Component

package.json, src/runtime/eval-expr.js
=> Fix filter call issue

.circleci/config.yml
=> ci: add circle branch

src/browser/create-el.js, src/browser/svg-tags.js, src/parser/parse-template.js, src/util/split-camel-str-2-obj.js
fix#321 同时处理了svg中其他可能含有大写标签名的情况
=> 处理svg中可能含有大写标签名的情况

src/view/for-node.js, src/view/text-node.js
- TextNode 的 _prev 似乎没有被用到
- ForNode 的 detach 方法似乎没有被掉用过，并且 ForNode 没有 ToPhase 方法，不存在 lifeCycle 属性
=> refactor: remove property and method since unused.

appveyor.yml, package.json, test/ssr/build-test.js
- add appveyor ci for win platform
- fix some win platform compatible bugs
=> ci: add Appveyor build & update some changes for win platform

.circleci/config.yml, .travis.yml, appveyor.yml, test/karma.conf.js
- add node v10 LTS for ci
- move coveralls from circleCI to travis CI
- change travis config for laterly support travis windows platform
=> ci: ci approve

types/index.d.ts
对 `ANode` 和 `ExprNode` 更详细的类型定义，以便在 san-ssr 中使用 strict 模式。
对应的 TypeGuards 目前在 san-ssr 中：https://github.com/baidu/san-ssr/blob/337faf7023c55/src/utils/type-guards.ts 。看 san 要不要把它也收进来。
=> feat: type definitions for ExprNodes and ANodes

types/index.d.ts
=> modify d.ts to support dynamic sub component

src/parser/parse-template.js, test/parse-template-error.spec.js
=> throw when parsing invalid attribute, closes #526

package-lock.json, package.json
- 具体 case 见：https://github.com/ecomfe/san-html-cases/commit/cfeb1163386660ba7ff620b681c1fdc448c15226
=> test: 升级 san-html-cases，增加 s-data 转义 case

example/todos-esnext/README.md
Scope of changes is restricted to docs only.
=> fix(docs): corrects a typo in project documentation

src/browser/create-el.js, src/browser/svg-tags.js
**删除的svg标签**
textpath
clippath
animateColor
**增加的svg标签**
linearGradient
radialGradient
stop
clipPath
=> 优化svg tags，兼容模板中的svg小写标签，增删一些标签

src/parser/unpack-anode.js
=> fix: add unpackANode exports

.gitignore, dist/index.js, package.json
=> build: 修改引用 main 入口，根据环境变量判断引用的包

example/todos-ts/src/todo/form.ts
=> fix:todo-ts edit

src/main.js, src/view/hydrate-component.js, test/build-reverse-test.js
=> [WIP] feat: ssr render-only

src/util/inherits.js, src/view/component.js, src/view/for-node.js, src/view/preheat-a-node.js
san 在实现 class 的继承、组件反解时 initdata 的拼接以及 traceBy 的处理时，使用了 new Function 这样的关键字，但 chrome extension 存在[内容安全策略](https://developer.chrome.com/docs/extensions/mv3/manifest/content_security_policy/#minimum-and-customized-content-security-policies)的限制，这导致相关的代码报错，从而引发组件无法渲染的问题
因此修改了上述相关代码，移除了 `new Function` 的使用
=> New function fixed

README.md
For the sole purpose of adhering to the team's unified requirements
=> update README.md to include special thanks to PowerSource Initiative
