baidu/san

- src/view/compile-js-source.js
- src/view/get-prop-handler.js
- test/element.spec.js
绑定 `draggable` 属性后，改变 model 的值，可以观察到 `draggable` 属性变为 `true` 后不再继续发生变化。
https://codepen.io/Dafrok/pen/ZKgZmm
> 提供动态 `draggable` 属性的支持

- tool/build.js
由于 uglify 没有设置 screw_ie8 选项，在 build 后部分被 uglify 压缩的文件中的对象键名的引号被去掉，导致在 IE6-8 中使用 class / for 等保留字做键名的对象抛出错误。
> 解决 class / for 保留字做键名时 uglify 后在 IE 下报错的问题

- tool/build.js
之前的配置，生成的 *.min.js 在 ie8 下面是无法运行的。`for, class, x.else` 这些情况没有处理
> Add missing screw_ie8 options

- .gitignore
- src/view/define-component.js
在项目中，基于业务考量（e.g. **单组件size**），曾尝试将 san 的 **组件开发** 和 **运行时环境** 分离。在这种情况下，递归调用 san 包装器包装时，因 san 的`defineComponent`内部无检验逻辑，会存在重复定义风险。该 pull request 增加了包装器的内部校验逻辑，并对异常使用情形抛出错误，方便框架使用者定位问题。
> 提高 defineComponet 方法友好性，避免重复定义，异常使用抛错

- src/view/component.js
- test/component.spec.js
刚本地merge 3.3.0-dev  发现似乎和主干是一样的，没merge下来新东西，不知道有没有问题~
> Fix121: 把 nextTick 函数的引用挂到 san 组件的实例上

- package.json
- typings/san.d.ts
添加万用 declaration file，姑且照顾一下 ts 用户。
注：由于 san 的 export 没有使用 CommonJS 2 规范，ts 没办法把 san 对象当作 default export，因此在 ts 中引用的时候只能 `import * as san from 'san'` 而不能写作 `import san from 'san'`，这点可能需要在文档里注明。
> resolve #128

- src/parser/parse-template.js
- test/if-directive.spec.js
- test/parse-template-error.spec.js
为 template 添加更好的语法错误报错信息 #61
关于标签匹配，san template 应符合此规则：
html5 中规定不允许闭合的标签（自闭合标签）不强制闭合，其他标签必须闭合。
> 自闭合标签有
> `<area>` `<base>` `<br>` `<col>` `<embed>` `<hr>` 
> `<img>` `<input>` `<keygen>` `<param>` `<source>` `<track>` `<wbr>`
即对于自闭合标签这么写是可以接受的：
```html
<input > or <input />
```
但这个不行
```html
<input>xxx</input>
```
对于非自闭合标签，强制进行闭合：
```html
<li></li> or <li />
```
html 语法错误提示优化包含以下：
其他的语法错误欢迎补充
> 为 template 添加更好的语法错误报错信息

- src/parser/parse-template.js
- test/element.spec.js
fix a bug, which occurred when using space around attribute's = operator, change the regexp, add space detect: `var attrReg = /([-:0-9a-z\(\)\[\]]+)(\s*=\s*(['"])([^\3]*?)\3)?\s*/ig;`
> fix error when using space around attribute's = operator

- src/view/component.js
supporting this:
```
<div id=root>
你好 <span>San Reverse</span>!
</div>
```
not only this:
```
<div id=root>
你好 <span>San Reverse</span>!
</div>
```
> reverse data bind to first comment node, not first child, of el.

- src/runtime/data.js
- src/view/component.js
san基于数据变化的信息做出对应的界面操作，for-node对数组类型的类splice方法做了很多优化操作，但是数据在通过组件属性传递的过程中直接用set方法，导致信息缺失，for-node优化无效
> 维持属性数据传递变化信息

- package.json
- 修正直接运行`npm run  test:coverage`无法触发`pretest`钩子的问题
- 删除冗余scripts代码
> pkg: fix `npm run  test:coverage` cannot run pretest hook bug

- .circleci/config.yml
- .travis.yml
- circle.yml
- package.json
- test/karma.conf.js
- 修正circle.ci 无法跑通的问题
- 升级circle.ci 的config文件至2.0，1.0将在八月停止使用
- 增加coveralls.io 覆盖度测试报告，合并之后请把`COVERALLS_REPO_TOKEN`换成https://coveralls.io/github/baidu/san 的`repo token`
- 增加travis.ci的配置
> ci: circle.ci approve

- tool/pack.js
将构建后dist目录中文件所用到的三个枚举类型：
- ExprType
- NodeType
- DataChangeType
在构建时，转换成字面量常量，进而减少gzip后代码体积：
san.min.js 减少 129 bytes（15558 ---> 15429）
san.spa.modern.min.js 减少 107 bytes（14372 ---> 14265）
> chore: change enum to const value

- src/view/component.js
- src/view/warn-override-super-prototype.js
没有直接 throw error 是考虑到有些开发者会进行再封装（比如 yubei），更新版本后项目就 break 掉了
> 增加一个覆盖 Component 原型的警告

- src/view/preheat-a-node.js
san中的子组件如果定义成h5原生标签同名的会有问题，如下面h5例子，也能复现问题，会有视频声音播放：
```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>start - hello</title>
</head>
<body>
san2
<script src="https://unpkg.com/san@3.7.5/dist/san.min.js"></script>
<script>
var Child = san.defineComponent({
template: '<p on-click="toggleProps">aaaaaa child props: {{props}}</p>',
initData: function () {
return {
};
},
toggleProps() {
this.data.set('props', false);
}
});
var MyApp = san.defineComponent({
template: `
<div>
<video s-ref="video" id="myde" style="width: 100px; height: 100px; background-color: gray;" duration="10"
src="http://wxsnsdy.tc.qq.com/105/20210/snsdyvideodownload?filekey=30280201010421301f0201690402534804102ca905ce620b1241b726bc41dcff44e00204012882540400&bizid=1023&hy=SH&fileparam=302c020101042530230204136 …
```
> fix video autoplay in background while component tagName is video

- src/view/for-node.js
- test/for-directive.spec.js
Make view do not refresh if irrelevant sibling props modified when `san-for` is used on an object.
> do not refresh if irrelevant props modified when san-for used on an object

- example/todos-esnext/src/filters.js
- example/todos-esnext/src/service.js
目前的todos-esnext中存在以下问题：
1.添加新的分类时，会出现所有的新分类的id都与已有分类的id重复。体现在选中新加的分类时，与新分类id一样的分类也会显示被选中，显示某一分类下的内容时，两个id相同的内容会同时显示出来。
2.todolist预期完成时间无法正常显示。
故做以下修改，望采纳~
>  fix category id repeat & fix formatedate

- types/index.d.ts
SanData 的类型缺一些东西，在这个 PR 中补充。这个变更是 https://github.com/searchfe/san-ssr/pull/18 中的一个依赖。
变更内容：
* Add return value for SanData `new()` method, for use cases where
`noImplicitAny` option is enabled
* Make `get()` argument  `expr` optional, for cases when getting
the whole data
> fix: type for SanData

- src/browser/auto-close-tags.js
- test/parse-template-error.spec.js
auto-close-tags 和 HTML5 中的 [void elements 列表](https://html.spec.whatwg.org/multipage/syntax.html#void-elements) 保持一致：增加 link、meta；去掉 keygen。
FIX
- 自关闭标签的开始标签上 `/` 是可选的（见 [syntax.html#start-tags](https://html.spec.whatwg.org/multipage/syntax.html#start-tags)），目前 link、meta 在 san 中必须加 `/`。
- 额外的问题是加 `/` 后又会触发 fecs 的 `Void tags should not close themeselves with "/"`。
BREAKING CHANGES
- keygen 不再是自关闭标签，必须手动关闭。
> 自关闭标签和 WHATWG/HTML5 保持一致

- CHANGELOG.md
- src/util/decode-html-entity.js
- types/index.d.ts
有两个 commit：
1. 3.9.0  的 types 更新：
- `textExpr` 在 ANode 压缩后可能是 `ATextNode`，也可能是 `AStringNode`
- 干掉 `raw` 和 `literal`，新增 `noValue`
- `SanData#get()` 的一个易用性功能 `get<string>()` 来得到 string，之前需要 `(get() as string)`
2. nbsp 应该映射到 unicode 00a0 (hex)，之前映射到了 20(hex)
> 修复：nbsp 的值、3.9.0 的 types

- package-lock.json
- src/view/component.js
- src/view/preheat-a-node.js
- test/component.spec.js
如果不兼容getComponentType还好，但是如果要兼容getComponentType，见component.spec.js中名为”identify subcomponent with reserved hot tag with getComponentType“的case。
想到的办法只有尝试看能不能用getComponentType(mockHotTagANode, data)来看看是否返回组件，但是因为无法得知getComponentType的具体实现，只能mock该方法使用tagName为hottag时的逻辑，如果用户是利用使用hottag的aNode上的其他属性做逻辑判断，则会漏判（概率比较小）。
此外，还有一个sideeffect就是，为了兼容getComponentType，只能在拿到this.data之后去preheat，这跟expose的phase矛盾了。
所以此PR请erik看一下，是否要兼容getComponentType的case，如果要兼容就有上面说的两个问题。
如果不兼容，那就轻松愉快了。
> feat: identify subcomponent with hot tag

- src/view/component.js
将 oldValue 替换为 value，否则当监听的数据改变时， value 值没得到更新而一直为初始值。
假如数据初始值是1，这样改变： 1->2->3->1，那么 3->1 这次改变不能触发 listener。
> fix: replace oldValue with value

- package-lock.json
- package.json
- src/view/slot-node.js
san-ssr 的输出格式较之前的提交：https://github.com/baidu/san/commit/8f07367f809cd1e57cfcfc9976e942e872a21237 https://github.com/baidu/san/commit/cd68628757bb95c8b65bb987462a8e773bd5d72c 已经有了较大变化。
目前 san-ssr 的渲染结果中，fragment 会输出 comment 标记，但是 slot 不会输出 comment 标记。
在反解时遇到 slot 尝试消耗 comment 标记与 san-ssr 行为不一致，会引入其他问题，因此将 slot-node 中相关代码移除。
测试了其他 case，没有发现问题：
```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>start - for</title>
</head>
<body>
<script src="./node_modules/san/dist/san.js"></script>
<div id="root">
<div><div>123456123456</div></div>
</div>
<script>
let container = san.defineComponent({
template: `
<div>
<slot/>
</div>
`
})
let MyApp = san.defineComponent({
components: { 'x-l': container },
template: '<div><x-l>{{ aaa | raw }}456{{ aaa | raw }}456</x-l></div>',
initData() { …
```
> fix: baidu/san-ssr#125

- src/view/component.js
- src/view/for-node.js
1. this.aNode._gfk 可能为 undefined，而 bind 的第一个参数为必填，因此这里判断一下，避免执行 bind(this.aNode._gfk, this.aNode) 时抛出异常
2. 修复 JSON.parse 时由转义符导致的异常
3. 修复 JSON.parse 后 Date 数据类型异常的问题
> fix unsafe-eval
